[package]
name = "a2lfile"
version = "0.8.0"
authors = ["Daniel Thaler <daniel@dthaler.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies.a2lmacros]
path = "a2lmacros"

[dependencies]
encoding = "0.2"
