[package]
name = "a2lmacros"
version = "0.1.0"
authors = ["Daniel Thaler <daniel@dthaler.de>"]
edition = "2018"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
